#!/usr/bin/env bash
set -euo pipefail
if test "$#" -ne 3; then echo "usage: conform.sh OUTPUT REPLAY OUTPUT_REPORT" >&2; exit 64; fi
bundle=$1; replay=$2; output=$3; checks='[]'
append(){ local id=$1 stage=$2 step=$3 state=$4 reason=$5 next=$6; checks=$(jq -c --arg id "$id" --arg stage "$stage" --arg step "$step" --arg state "$state" --arg reason "$reason" --arg next "$next" '.+[{id:$id,stage:$stage,step:$step,state:$state,reason:$reason,next_operation:$next,unknown_class:null}]' <<<"$checks"); }
expected=$(printf '%s\n' checksums.txt edges.ndjson nodes.ndjson portfolio.json unknowns.ndjson); actual=$(find "$bundle" -mindepth 1 -maxdepth 1 -type f -printf '%f\n' | sort)
if test "$actual" = "$expected"; then append EXACT_FILE_SET OUTPUT VERIFY_EXACT_FILE_SET CLOSED EXACT_FILE_SET_OBSERVED NONE; else append EXACT_FILE_SET OUTPUT VERIFY_EXACT_FILE_SET REFUTED FILE_SET_MISMATCH RESTORE_EXACT_FILE_SET; fi
if jq -e '.schema=="gooo/advisory-connector/portfolio/v1" and .domain_count==3 and (.domains|length)==3 and .edge_count==3 and .authority=={effect:"READ_ONLY",external_required_gates:0}' "$bundle/portfolio.json" >/dev/null 2>&1; then append PORTFOLIO_IDENTITY IDENTITY VERIFY_PORTFOLIO_IDENTITY CLOSED PORTFOLIO_IDENTITY_VERIFIED NONE; else append PORTFOLIO_IDENTITY IDENTITY VERIFY_PORTFOLIO_IDENTITY REFUTED PORTFOLIO_IDENTITY_MISMATCH RESTORE_PORTFOLIO_IDENTITY; fi
if jq -s -e --slurpfile edges "$bundle/edges.ndjson" --slurpfile portfolio "$bundle/portfolio.json" '. as $nodes | ($nodes|length)==$portfolio[0].node_count and all($edges[]; . as $edge | any($nodes[];.kind==$edge.from.kind and .id==$edge.from.id) and any($nodes[];.kind==$edge.to.kind and .id==$edge.to.id))' "$bundle/nodes.ndjson" >/dev/null 2>&1; then append GRAPH_ENDPOINTS GRAPH VERIFY_GRAPH_ENDPOINTS CLOSED GRAPH_ENDPOINTS_VERIFIED NONE; else append GRAPH_ENDPOINTS GRAPH VERIFY_GRAPH_ENDPOINTS REFUTED GRAPH_ENDPOINT_MISMATCH RESTORE_GRAPH_ENDPOINTS; fi
if jq -s -e --slurpfile unknowns "$bundle/unknowns.ndjson" '([.[]|select(.state=="UNKNOWN")]) as $expected | $unknowns as $actual | $expected==$actual and all($expected[];(.stage|type)=="string" and (.step|type)=="string" and (.reason|type)=="string" and (.unknown_class|type)=="string" and (.next_operation|type)=="string" and .next_operation!="NONE")' "$bundle/edges.ndjson" >/dev/null 2>&1; then append UNKNOWN_TUPLES UNCERTAINTY VERIFY_UNKNOWN_TUPLES CLOSED UNKNOWN_TUPLES_VERIFIED NONE; else append UNKNOWN_TUPLES UNCERTAINTY VERIFY_UNKNOWN_TUPLES REFUTED UNKNOWN_TUPLE_INCOMPLETE RESTORE_UNKNOWN_TUPLES; fi
if (cd "$bundle" && sha256sum -c checksums.txt >/dev/null 2>&1); then append SHA256_CHECKSUMS DIGEST VERIFY_SHA256_CHECKSUMS CLOSED SHA256_CHECKSUMS_VERIFIED NONE; else append SHA256_CHECKSUMS DIGEST VERIFY_SHA256_CHECKSUMS REFUTED SHA256_CHECKSUM_MISMATCH RESTORE_OUTPUT_CONTENT; fi
replay_equal=true; for file in checksums.txt edges.ndjson nodes.ndjson portfolio.json unknowns.ndjson; do cmp -s "$bundle/$file" "$replay/$file" || replay_equal=false; done
if test "$replay_equal" = true; then append DETERMINISTIC_REPLAY REPLAY VERIFY_DETERMINISTIC_REPLAY CLOSED DETERMINISTIC_REPLAY_VERIFIED NONE; else append DETERMINISTIC_REPLAY REPLAY VERIFY_DETERMINISTIC_REPLAY REFUTED NONDETERMINISTIC_CONNECTOR_OUTPUT RESTORE_DETERMINISTIC_CONNECTOR; fi
jq -S -n --argjson checks "$checks" '([$checks[]|select(.state=="CLOSED")]|length) as $closed|([$checks[]|select(.state=="REFUTED")]|length) as $refuted|([$checks[]|select(.state!="CLOSED")][0]//null) as $first|{schema:"gooo/advisory-connector/conformance/v1",decision:(if $refuted>0 then "FAIL_CLOSED" else "CONFORMANT" end),summary:{total:6,closed:$closed,unknown:0,refuted:$refuted,required_files:5,external_required_gates:0},claim:(if $first==null then {state:"CLOSED",stage:null,step:null,reason:"CONNECTOR_OUTPUT_CONFORMANT",next_operation:"NONE",unknown_class:null} else {state:$first.state,stage:$first.stage,step:$first.step,reason:$first.reason,next_operation:$first.next_operation,unknown_class:$first.unknown_class} end),checks:$checks}' > "$output"
