#!/usr/bin/env bash
set -euo pipefail
if test "$#" -ne 11; then echo "usage: observe.sh ROOT PROMOTION RELEASES INPUT_ROOT CONNECTOR_ROOT CONFORMANCE CHECKSUM_RUNTIME RUNTIME CONNECTOR_EXIT PUBLIC_STATE OUTPUT" >&2; exit 64; fi
root=$1; promotion=$2; releases=$3; inputs=$4; connector=$5; conformance=$6; checksum=$7; runtime=$8; connector_exit=$9; public_state=${10}; output=${11}; lock="$root/contracts/release-locks-v1.json"
work=$(mktemp -d); trap 'rm -rf "$work"' EXIT
json_or_null(){ if test -f "$1" && jq -e . "$1" >/dev/null 2>&1; then cp "$1" "$2"; else printf 'null\n' > "$2"; fi; }
json_or_null "$promotion" "$work/promotion.json"; json_or_null "$releases" "$work/releases.json"; json_or_null "$connector/portfolio.json" "$work/portfolio.json"; json_or_null "$conformance" "$work/conformance.json"; json_or_null "$checksum" "$work/checksum.json"; json_or_null "$runtime" "$work/runtime.json"
: > "$work/nodes.ndjson"; : > "$work/edges.ndjson"; : > "$work/unknowns.ndjson"; test -f "$connector/nodes.ndjson" && cp "$connector/nodes.ndjson" "$work/nodes.ndjson"; test -f "$connector/edges.ndjson" && cp "$connector/edges.ndjson" "$work/edges.ndjson"; test -f "$connector/unknowns.ndjson" && cp "$connector/unknowns.ndjson" "$work/unknowns.ndjson"
input_count=0; for domain in local-ledger design-evidence infra-evidence; do test -f "$inputs/$domain/bundle-a/project.json" && test -f "$inputs/$domain/bundle-a/relations.ndjson" && input_count=$((input_count+1)); done
output_files=0; test -d "$connector" && output_files=$(find "$connector" -mindepth 1 -maxdepth 1 -type f | wc -l | tr -d ' ')
jq -S -n --arg public_state "$public_state" --argjson connector_exit "$connector_exit" --argjson input_count "$input_count" --argjson output_files "$output_files" --slurpfile lock "$lock" --slurpfile promotion "$work/promotion.json" --slurpfile releases "$work/releases.json" --slurpfile portfolio "$work/portfolio.json" --slurpfile conformance "$work/conformance.json" --slurpfile checksum "$work/checksum.json" --slurpfile runtime "$work/runtime.json" --slurpfile nodes "$work/nodes.ndjson" --slurpfile edges "$work/edges.ndjson" --slurpfile unknowns "$work/unknowns.ndjson" '
  ($nodes|length) as $node_count|($edges|length) as $edge_count|($unknowns|length) as $unknown_count|([$edges[].to|(.kind+"\u0000"+.id)]|unique|length) as $anchors|
  (all($edges[] as $edge;([$nodes[]|select(.kind==$edge.from.kind and .id==$edge.from.id)]|length)==1 and ([$nodes[]|select(.kind==$edge.to.kind and .id==$edge.to.id)]|length)==1)) as $endpoints_ok|
  (all($unknowns[];(.stage|type)=="string" and (.step|type)=="string" and (.reason|type)=="string" and (.unknown_class|type)=="string" and (.next_operation|type)=="string" and .next_operation!="NONE")) as $unknowns_complete|
  ($unknowns[0]//null) as $first_unknown|
  {schema:"gooo/advisory-connector/facts/v1",public_state:$public_state,core_release_verified:true,promotion:{identity_verified:($promotion[0]!=null),decision:$promotion[0].decision,state:$promotion[0].promotion.state},domain_releases:{identity_verified:([$releases[0].consumers[]?|select(.identity_verified==true and .archive_verified==true)]|length),total:3},input:{bundles:$input_count,total:3,connector_exit:$connector_exit},output:{files:$output_files,nodes:$node_count,edges:$edge_count,unknowns:$unknown_count,node_graph_consistent:($portfolio[0]!=null and $portfolio[0].node_count==$node_count and $endpoints_ok),edge_graph_consistent:($portfolio[0]!=null and $portfolio[0].edge_count==$edge_count),shared_specification_anchors:$anchors,unknown_tuples_complete:$unknowns_complete},conformance:$conformance[0],checksum_guard:$checksum[0],runtime:$runtime[0],contract:$lock[0].connector_contract,
   connector_decision:(if $input_count<3 then {state:"UNKNOWN",stage:"INPUT",step:"OBSERVE_CANONICAL_INPUT_BUNDLES",reason:"CANONICAL_INPUT_BUNDLE_UNAVAILABLE",unknown_class:"DIRECT_MISSING",next_operation:"PROVIDE_CANONICAL_INPUT_BUNDLES"} elif $connector_exit!=0 or $portfolio[0]==null then {state:"REFUTED",stage:"GENERATION",step:"GENERATE_PORTFOLIO_GRAPH",reason:"CONNECTOR_GENERATION_FAILED",unknown_class:null,next_operation:"RESTORE_CONNECTOR_GENERATION"} elif $unknown_count>0 then {state:"UNKNOWN",stage:$first_unknown.stage,step:$first_unknown.step,reason:$first_unknown.reason,unknown_class:$first_unknown.unknown_class,next_operation:$first_unknown.next_operation} else {state:"CLOSED",stage:null,step:null,reason:"ADVISORY_CONNECTOR_DECISION_CLOSED",unknown_class:null,next_operation:"NONE"} end)}' > "$output"
